### ISSUE TITLE
Create dedicated pre-setup role in matrix-docker-ansible-deploy

### ISSUE THREAD

**Issue by Michael-Hollister** [circles-project/matrix-docker-ansible-deploy#4]
Based on recent work in commit https://github.com/circles-project/matrix-docker-ansible-deploy/commit/8b6a9b5bfa8ed38c5a9073affca3e5af34599aac it seems like there is a need for a new role with commands that run on the server to set up base system variables before the rest of the playbook runs.

We should talk to Slavi upstream, create the role, and submit a PR.

**Comment by cvwright** [comment]
I could have sworn that the upstream playbook had something similar(-ish) to this in recent versions.  But now I'm looking and I can't find anything like that.

> We should talk to Slavi upstream, create the role, and submit a PR.

Yes 👍

**Comment by Michael-Hollister** [comment]
Looking again at this, I figured out a way to get the auxiliary role to be ran twice in `setup.yml`, along with it being parameterized. The change is simple enough and since usage of this feature is a limited use-case, I won't be up-streaming of this change unless you think otherwise.

Fixed in https://github.com/circles-project/matrix-docker-ansible-deploy/commit/53eaa76197a8c4223fc91952ae091cc80800b98a
